server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Compressão GZIP para otimizar o carregamento
    gzip on;
    gzip_min_length 1000;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        # Tenta carregar o arquivo, se não achar, joga para o index.html (Vue Router)
        try_files $uri $uri/ /index.html;
    }

    # Cache agressivo para arquivos estáticos gerados no build
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public, max-age=15552000, immutable";
    }
}
