# Generated by Django 4.2.30 on 2026-07-01 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cadastros", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Movimentacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_evento",
                    models.CharField(
                        choices=[
                            ("PROTOCOLO", "Protocolo"),
                            ("DISTRIBUICAO", "Distribuição"),
                            ("CONCLUSAO", "Conclusão"),
                            ("REJEICAO", "Rejeição"),
                            ("DILIGENCIA_INICIADA", "Diligência Iniciada"),
                            ("DILIGENCIA_RESOLVIDA", "Diligência Resolvida"),
                            ("ARQUIVAMENTO", "Arquivamento"),
                            ("OBSERVACAO_SIMPLES", "Observação Simples"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de Evento",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Descrição / Despacho / Motivo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimentação",
                "verbose_name_plural": "Movimentações",
                "ordering": ["data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="Processo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_protocolo",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Número de Protocolo"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AGUARDANDO_DISTRIBUICAO", "Aguardando Distribuição"),
                            ("EM_ANALISE", "Em Análise"),
                            ("EM_DILIGENCIA", "Em Diligência"),
                            ("CONCLUIDO", "Concluído"),
                            ("ARQUIVADO", "Arquivado"),
                            ("REJEITADO", "Rejeitado"),
                        ],
                        default="AGUARDANDO_DISTRIBUICAO",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_limite",
                    models.DateField(blank=True, null=True, verbose_name="Data Limite"),
                ),
                (
                    "data_atribuicao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Atribuição"
                    ),
                ),
                (
                    "interessados",
                    models.ManyToManyField(
                        blank=True,
                        related_name="processos_como_interessado",
                        to="cadastros.remetente",
                        verbose_name="Interessados",
                    ),
                ),
                (
                    "prioridade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processos",
                        to="cadastros.nivelprioridade",
                        verbose_name="Prioridade",
                    ),
                ),
                (
                    "procurador_atribuido",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processos_atribuidos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Procurador Atribuído",
                    ),
                ),
                (
                    "remetente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processos_como_remetente",
                        to="cadastros.remetente",
                        verbose_name="Remetente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Processo",
                "verbose_name_plural": "Processos",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="SolicitacaoDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao_necessidade",
                    models.TextField(verbose_name="Descrição da Necessidade"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("ENVIADA", "Enviada"),
                            ("ATENDIDA", "Atendida"),
                            ("REJEITADA", "Rejeitada"),
                        ],
                        default="PENDENTE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_solicitacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Solicitação"
                    ),
                ),
                (
                    "data_envio_email",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Envio do E-mail"
                    ),
                ),
                (
                    "data_conclusao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Conclusão"
                    ),
                ),
                (
                    "motivo_rejeicao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Motivo da Rejeição"
                    ),
                ),
                (
                    "observacao_chefia",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observação da Chefia"
                    ),
                ),
                (
                    "movimentacao_origem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solicitacoes_originadas",
                        to="gestao.movimentacao",
                        verbose_name="Movimentação de Origem",
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitacoes_documento",
                        to="gestao.processo",
                        verbose_name="Processo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação de Documento (Diligência)",
                "verbose_name_plural": "Solicitações de Documento (Diligências)",
                "ordering": ["-data_solicitacao"],
            },
        ),
        migrations.AddField(
            model_name="movimentacao",
            name="processo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movimentacoes",
                to="gestao.processo",
                verbose_name="Processo",
            ),
        ),
        migrations.AddField(
            model_name="movimentacao",
            name="usuario_responsavel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movimentacoes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário Responsável",
            ),
        ),
        migrations.CreateModel(
            name="Anexo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="anexos/",
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "tipo_anexo",
                    models.CharField(
                        choices=[
                            ("INICIAL", "Inicial"),
                            ("RESPOSTA", "Resposta"),
                            ("DILIGENCIA", "Diligência"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Anexo",
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Número do Documento",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "movimentacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anexos",
                        to="gestao.movimentacao",
                        verbose_name="Movimentação",
                    ),
                ),
                (
                    "tipo_documento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anexos",
                        to="cadastros.tipodocumento",
                        verbose_name="Tipo de Documento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anexo",
                "verbose_name_plural": "Anexos",
            },
        ),
    ]
