# Generated by Django 5.2.15 on 2026-07-02 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0001_initial"),
        ("gestao", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="anexo",
            name="observacao",
            field=models.TextField(blank=True, null=True, verbose_name="Observação"),
        ),
        migrations.AddField(
            model_name="anexo",
            name="processo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anexos",
                to="gestao.processo",
                verbose_name="Processo (acesso direto)",
            ),
        ),
        migrations.AddField(
            model_name="processo",
            name="data_origem",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Origem"
            ),
        ),
        migrations.AddField(
            model_name="processo",
            name="notificar_remetente",
            field=models.BooleanField(
                default=False, verbose_name="Notificar Remetente"
            ),
        ),
        migrations.AddField(
            model_name="processo",
            name="numero_origem",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Número de Origem"
            ),
        ),
        migrations.AddField(
            model_name="processo",
            name="observacoes",
            field=models.TextField(blank=True, null=True, verbose_name="Observações"),
        ),
        migrations.AddField(
            model_name="processo",
            name="tipo_processo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processos_tipo",
                to="cadastros.tipodocumento",
                verbose_name="Tipo de Processo",
            ),
        ),
    ]
