# Generated by Django 5.2.15 on 2026-07-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gestao",
            "0002_anexo_observacao_anexo_processo_processo_data_origem_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="anexo",
            name="tipo_anexo",
            field=models.CharField(
                choices=[
                    ("INICIAL", "Inicial"),
                    ("RESPOSTA", "Resposta"),
                    ("DILIGENCIA", "Diligência"),
                    ("OUTROS", "Outros"),
                ],
                max_length=20,
                verbose_name="Tipo de Anexo",
            ),
        ),
    ]
