# Generated by Django 5.2.15 on 2026-07-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0003_add_tipo_anexo_outros"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movimentacao",
            name="tipo_evento",
            field=models.CharField(
                choices=[
                    ("PROTOCOLO", "Protocolo"),
                    ("DISTRIBUICAO", "Distribuição"),
                    ("CONCLUSAO", "Conclusão"),
                    ("REJEICAO", "Rejeição"),
                    ("DILIGENCIA_INICIADA", "Diligência Iniciada"),
                    ("DILIGENCIA_RESOLVIDA", "Diligência Resolvida"),
                    ("ARQUIVAMENTO", "Arquivamento"),
                    ("DESARQUIVAMENTO", "Desarquivamento"),
                    ("DEVOLUCAO", "Devolução"),
                    ("ANEXO_ARQUIVO", "Anexo de Arquivo"),
                    ("OBSERVACAO_SIMPLES", "Observação Simples"),
                ],
                max_length=30,
                verbose_name="Tipo de Evento",
            ),
        ),
    ]
