# Generated by Django 5.2.15 on 2026-07-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0004_add_tipoevento_desarquivamento_devolucao_anexo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processo",
            name="status",
            field=models.CharField(
                choices=[
                    ("AGUARDANDO_DISTRIBUICAO", "Aguardando Distribuição"),
                    ("DEVOLVIDO", "Devolvido"),
                    ("EM_ANALISE", "Em Análise"),
                    ("EM_DILIGENCIA", "Em Diligência"),
                    ("CONCLUIDO", "Concluído"),
                    ("ARQUIVADO", "Arquivado"),
                    ("REJEITADO", "Rejeitado"),
                ],
                default="AGUARDANDO_DISTRIBUICAO",
                max_length=30,
                verbose_name="Status",
            ),
        ),
    ]
