# Generated by Django 5.2.15 on 2026-07-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0005_add_status_devolvido"),
    ]

    operations = [
        migrations.AddField(
            model_name="processo",
            name="numero_sei",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Número SEI"
            ),
        ),
    ]
