# Generated by Django 5.2.15 on 2026-07-07 19:13

import django.core.validators
import gestao.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0006_processo_numero_sei"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anexo",
            name="arquivo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=gestao.models.upload_path_anexo,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    )
                ],
                verbose_name="Arquivo",
            ),
        ),
    ]
