# Generated by Django 5.2.15 on 2026-07-07 19:42

import django.db.models.deletion
import gestao.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0007_anexo_upload_path_validator"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkCompartilhamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Token",
                    ),
                ),
                (
                    "data_expiracao",
                    models.DateTimeField(
                        default=gestao.models.default_expiracao,
                        verbose_name="Data de Expiração",
                    ),
                ),
                (
                    "arquivo_gerado",
                    models.FileField(
                        upload_to="autos_exportados/", verbose_name="Arquivo Gerado"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado Em"),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links_compartilhamento",
                        to="gestao.processo",
                        verbose_name="Processo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Link de Compartilhamento",
                "verbose_name_plural": "Links de Compartilhamento",
                "ordering": ["-criado_em"],
            },
        ),
    ]
