# Generated by Django 5.2.15 on 2026-07-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0009_processo_data_resposta_procurador"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movimentacao",
            name="tipo_evento",
            field=models.CharField(
                choices=[
                    ("PROTOCOLO", "Protocolo"),
                    ("DISTRIBUICAO", "Distribuição"),
                    ("CONCLUSAO", "Conclusão"),
                    ("REJEICAO", "Rejeição"),
                    ("DILIGENCIA_INICIADA", "Diligência Iniciada"),
                    ("DILIGENCIA_RESOLVIDA", "Diligência Resolvida"),
                    ("ARQUIVAMENTO", "Arquivamento"),
                    ("DESARQUIVAMENTO", "Desarquivamento"),
                    ("FINALIZACAO", "Finalização"),
                    ("DEVOLUCAO", "Devolução"),
                    ("ANEXO_ARQUIVO", "Anexo de Arquivo"),
                    ("OBSERVACAO_SIMPLES", "Observação Simples"),
                ],
                max_length=30,
                verbose_name="Tipo de Evento",
            ),
        ),
        migrations.AlterField(
            model_name="processo",
            name="status",
            field=models.CharField(
                choices=[
                    ("AGUARDANDO_DISTRIBUICAO", "Aguardando Distribuição"),
                    ("DEVOLVIDO", "Devolvido"),
                    ("EM_ANALISE", "Em Análise"),
                    ("EM_DILIGENCIA", "Em Diligência"),
                    ("CONCLUIDO", "Concluído"),
                    ("FINALIZADO", "Finalizado"),
                    ("ARQUIVADO", "Arquivado"),
                    ("REJEITADO", "Rejeitado"),
                ],
                default="AGUARDANDO_DISTRIBUICAO",
                max_length=30,
                verbose_name="Status",
            ),
        ),
    ]
