# Generated by Django 4.2.30 on 2026-07-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NivelPrioridade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=100, verbose_name="Descrição"),
                ),
                ("prazo_dias", models.IntegerField(verbose_name="Prazo (dias)")),
            ],
            options={
                "verbose_name": "Nível de Prioridade",
                "verbose_name_plural": "Níveis de Prioridade",
                "ordering": ["prazo_dias"],
            },
        ),
        migrations.CreateModel(
            name="Remetente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_razao_social",
                    models.CharField(
                        max_length=255, verbose_name="Nome / Razão Social"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="E-mail"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Telefone"
                    ),
                ),
                (
                    "tipo_pessoa",
                    models.CharField(
                        choices=[
                            ("FISICA", "Física"),
                            ("JURIDICA", "Jurídica"),
                            ("ORGAO_PUBLICO", "Órgão Público"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Pessoa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Remetente",
                "verbose_name_plural": "Remetentes",
                "ordering": ["nome_razao_social"],
            },
        ),
        migrations.CreateModel(
            name="TipoDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=255, verbose_name="Descrição"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "verbose_name": "Tipo de Documento",
                "verbose_name_plural": "Tipos de Documento",
                "ordering": ["descricao"],
            },
        ),
    ]
