# Generated by Django 5.2.15 on 2026-07-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="remetente",
            name="doc",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="CPF / CNPJ"
            ),
        ),
    ]
