# Generated by Django 5.2.15 on 2026-07-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0002_remetente_doc"),
    ]

    operations = [
        migrations.AddField(
            model_name="remetente",
            name="doc_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=64,
                null=True,
                verbose_name="Hash do documento (busca)",
            ),
        ),
        migrations.AddField(
            model_name="remetente",
            name="telefone_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=64,
                null=True,
                verbose_name="Hash do telefone (busca)",
            ),
        ),
        migrations.AlterField(
            model_name="remetente",
            name="doc",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="CPF / CNPJ (criptografado)",
            ),
        ),
        migrations.AlterField(
            model_name="remetente",
            name="telefone",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Telefone (criptografado)",
            ),
        ),
    ]
